### ISSUE TITLE
Olá :P

### ISSUE THREAD

**Issue by rodrigogs** [EduApps-CDG/DescicloBot#1]
Vi que você está usando minha lib do xvideos

https://github.com/EduApps-CDG/DescicloBot/blob/c63b54a3003745e99dcb51553860862d254858be/cmd/nsfw/xvideos.js#L1

Me deu até um gás pra escrever mais funcionalidades pra ela. Acho que vou começar pelo search.

**Comment by EduApps-CDG** [comment]
Ficou muito bom, mas também tive que adaptar umas coisas.
![image](https://user-images.githubusercontent.com/32627482/135589836-769ce5f5-4ce4-410f-866b-f77dbb38f6d5.png)

**Comment by tuzinrs** [comment]
Pérolas

**Comment by rodrigogs** [comment]
Kkkkkkkkk

É lento por causa do puppeteer. Infelizmente precisa carregar o JS da página pra carregar algumas infos do detalhe do vídeo... mas quem sabe tem um jeito mais ixpertinho de fazer isso.

**Comment by EduApps-CDG** [comment]
> mas quem sabe tem um jeito mais ixpertinho de fazer isso.
O Xvideos deve ter uma API por ai no domínio. Até porque o Android não pode executar comandos DB direto. E eles tem um app pra android.

Acho que a melhor maneira seria monitorar o caminho do app android e ver onde ele vai

**Comment by rodrigogs** [comment]
> > mas quem sabe tem um jeito mais ixpertinho de fazer isso.
> 
> O Xvideos deve ter uma API por ai no domínio. Até porque o Android não pode executar comandos DB direto. E eles tem um app pra android.
> 
> Acho que a melhor maneira seria monitorar o caminho do app android e ver onde ele vai

É uma ótima ideia, se eles não tem nenhum tipo de proteção.
